---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
---
spring:
  profiles: subject
words: I,You,He,She,It

---
spring:
  profiles: verb
words: corrioo,supoo,teníaa,vioo,compróo

---
spring:
  profiles: adjetive
words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  profiles: article
words: a,the

---
spring:
  profiles: noun
words: boat,book,vote,seat,backpack,partition,groundhog



