---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

words: corrio,supo,tenía,vio,compró


---
spring:
  profiles: subject
words: I,You,He,She,It

---
spring:
  profiles: verb
words: corrio,supo,tenía,vio,compró


